kumuluzee:
  name: orders-catalog
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/OrderCatalogDS
      connection-url: jdbc:postgresql://localhost:5433/ordercatalog
      username: postgres
      password: postgres
      pool:
        max-size: 3
  health:
    checks:
      data-source-health-check:
        - jndi-name: jdbc/OrderCatalogDS
          type: readiness
  metrics:
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /v1/orders/*
        status-codes: "200,201,204,400,404,500"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                    <Configuration name="orders">
                        <Appenders>
                            <Console name="console" target="SYSTEM_OUT">
                                <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                            </Console>
                        </Appenders>
                        <Loggers>                 
                            <!-- Default logger -->
                            <Root level="all">
                                <AppenderRef ref="console" level="info" />
                            </Root>
                        </Loggers>
                    </Configuration>'
rest-properties:
  maintenance-mode: false
  broken: false
